// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbPJeB9KiuiRj9wnoRBuhg7EDld2P2y2o',
    appId: '1:1000849427449:web:94d088d850d24ffc18cb28',
    messagingSenderId: '1000849427449',
    projectId: 'flutterkpu',
    authDomain: 'flutterkpu.firebaseapp.com',
    storageBucket: 'flutterkpu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRrBaNm6KDiBdjqn1pBFne16ytCj6gKi0',
    appId: '1:1000849427449:android:fe29c6f1f140597a18cb28',
    messagingSenderId: '1000849427449',
    projectId: 'flutterkpu',
    storageBucket: 'flutterkpu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhszS_90a6v-xIE4jycgULY8Ox1pJ4lI',
    appId: '1:1000849427449:ios:849ae777af540db518cb28',
    messagingSenderId: '1000849427449',
    projectId: 'flutterkpu',
    storageBucket: 'flutterkpu.firebasestorage.app',
    iosBundleId: 'com.example.projectKpu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhszS_90a6v-xIE4jycgULY8Ox1pJ4lI',
    appId: '1:1000849427449:ios:849ae777af540db518cb28',
    messagingSenderId: '1000849427449',
    projectId: 'flutterkpu',
    storageBucket: 'flutterkpu.firebasestorage.app',
    iosBundleId: 'com.example.projectKpu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbPJeB9KiuiRj9wnoRBuhg7EDld2P2y2o',
    appId: '1:1000849427449:web:754b41c6dd04726118cb28',
    messagingSenderId: '1000849427449',
    projectId: 'flutterkpu',
    authDomain: 'flutterkpu.firebaseapp.com',
    storageBucket: 'flutterkpu.firebasestorage.app',
  );
}
